### ISSUE TITLE
请教，国外下载不完整

### ISSUE THREAD

**Issue by Biuyan** [thomaswcy/Annie#1]
用danny的节点会出现以下问题，下载的文件会变成不完整的.webm.part，用我自己的节点可以正常下载。不清楚是什么情况，国内下载没有问题。
[youtube] 7hLzBveTdJ0: Downloading webpage
WARNING: [youtube] Unable to download webpage: <urlopen error _ssl.c:1114: The handshake operation timed out>
[youtube] 7hLzBveTdJ0: Downloading android player API JSON
WARNING: [youtube] <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>. Retrying ...
[youtube] 7hLzBveTdJ0: Downloading android player API JSON (retry #1)
[youtube] 7hLzBveTdJ0: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: <urlopen error _ssl.c:1114: The handshake operation timed out>
[youtube] 7hLzBveTdJ0: Downloading web player API JSON
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = YIwr0FOWnpb32Yn10L- ; player = None
Cannot decrypt nsig without player_url; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
[youtube] 7hLzBveTdJ0: Downloading initial data API JSON
[info] 7hLzBveTdJ0: Downloading 1 format(s): 303+251
[download] Got server HTTP error: <urlopen error _ssl.c:1114: The handshake operation timed out>. Retrying (attempt 1 of 10) ...
[download] Destination: C:\Users\WIN 10\Downloads\FP2 Highlights _ 2022 Saudi Arabia Grand Prix.f303.webm
[download]  20.8% of 92.67MiB at 20.76MiB/s ETA 00:03

**Comment by TakumiBC** [comment]
现在解决了吗？
